### ISSUE TITLE
I cannot get into Client Hub

### ISSUE THREAD

**Issue by ElaineMills** [CIWM/Client-Hub#10]
Hi, 

I have been trying to log into the client hub and I think I must have forgotten my password. When I try to get onto the site, after inputting my log in details I get sent to the screen below 

[redirect loop clienthub.docx](https://github.com/CIWM/Client-Hub/files/1148/redirect.loop.clienthub.docx)

I have also tried clicking forgot password and it does not recognise my username(elaine.mills) or my email address (elaine.mills@ciwm.co.uk) and I get this... 

[SESSKEY.docx](https://github.com/CIWM/Client-Hub/files/1149/SESSKEY.docx)

Please can you let me know what I am doing wrong?

Thanks
Elaine

**Comment by nick69g** [comment]
I've reset password.

http://clienthub.ciwm.co.uk

Username: elaine.mills@ciwm.co.uk
Pa$$word: Pa$$word1

Let me know if you still have difficulties.

**Comment by ElaineMills** [comment]
Hi Nick,

No I still cannot get in, how do I open this again as it is not resolved? 

is it anything to do with the update emails that we get sometimes?

**Comment by ElaineMills** [comment]
ignore above about reopening, commenting again seems to do that!

**Comment by nick69g** [comment]
Can you please confirm what you are trying to do:

The URL is: http://clienthub.ciwm.co.uk/
Username: elaine.mills@ciwm.co.uk
Password: Pa$$word1

I have just accessed the above with these details and it works fine.

**Comment by ElaineMills** [comment]
Hi Nick,

In response to the below, I have logged into both the Knowledge Hub and Client Hub. I don't have any idea what was gong on yesterday because I haven't done anything different today.

I'll close this now and let you know if I have any further issues. 

Thanks
Elaine


From: Nick Garrod [mailto:Nick.garrod@revisesustainability.com] 
Sent: 04 August 2015 20:05
To: Elaine Mills
Subject: Log into hub

Hi Elaine

Were you able to log into the Hub? If not, let me know what you are trying and I’ll see if I can help you further.

Nick

**Comment by nick69g** [comment]
This appeared to be an IT issue as the users end and resolved itself. No action was required.
