### ISSUE TITLE
Sodexo - client report

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#11]
I need to send a report to Sodexo on learner assessment passes but I noticed that on this report Richard McEwan is still showing as scoring 61%. Please can you confirm how to download an accurate assessment report from the client hub.Here's a screenshot of the one I'm using. 
![screenshot assessment report](https://cloud.githubusercontent.com/assets/13269824/9107746/bfe2fd70-3c21-11e5-9b82-b25c604db64b.jpg)

**Comment by nick69g** [comment]
Your approach is the correct one and a manually entered score should pull through. I've just done a Google search and seen that someone else has reported this as a Moodle issue - so it could be a bug. I'd need to look into it further.

I assume you will be exporting the report data to Excel? So maybe manually amend the score in the Excel file as a temporary measure?

I'll see what I can find out about this.

**Comment by AnnaHavard** [comment]
Thanks Nick, my concern with editing the figure is are any of the others wrong? For example I find it hard to believe that no-one has attempted the assessment twice.

**Comment by nick69g** [comment]
The settings have now changed so that learners automatically get two attempts without having select to start a new attempt. Moodle will record the highest score. Hopefully other people who attempted it twice with the older settings selected to undertake a new attempt - in which case the ascore should be accurate.

**Comment by nick69g** [comment]
This relates to the WasteSmart Assessment issue regarding learner attempts which has been rectified by the Moodle settings.

It appears as though once Moodle has recorded a score in the grades report, although it can be overridden, the overridden score does not get pulled through to the learner report. This appears to be a documented Moodle bug https://tracker.moodle.org/browse/MDL-42870

Now that the attempts settings have been updated, the recording of an incorrect score should not happen again.
