### ISSUE TITLE
Course sharing settings

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#12]
Should we have WasteSmart as an ‘open sharing’ course that is licensed rather than ‘closed sharing’? If we change it to open sharing I think it will automatically be available for any company to use if they have available licences? Currently we have to allocate the course to each new company we set up. 

![image](https://cloud.githubusercontent.com/assets/13269824/9110690/bcbe6c2c-3c37-11e5-913a-2a033541205b.png)

**Comment by nick69g** [comment]
Yes that's OK - "open sharing" makes it available to everyone - providing they have a license or have been enrolled onto it.

**Comment by AnnaHavard** [comment]
Thanks, I have changed this course and the other standard courses e.g Waste Aware, Introduction to Waste Legislation, to open sharing.



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image352d04.JPG@2690333f.4097a386]<http://>

[cid:imageccde82.PNG@b0efb68a.4c8c5583]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.
