### ISSUE TITLE
open sharing settings

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#13]
Following the query yesterday I set up a new company and user today; Ground Control, Philip Trehern and used licensing to give him access to WasteSmart. When I logged in as him to test his access the WasteSmart course wasn't shown on his profile.

Does this mean that even when a course is open sharing it still has to be assigned to the company for users to access it?

![image](https://cloud.githubusercontent.com/assets/13269824/9136327/ab68d71a-3d0d-11e5-92b8-e92c1aaa4c01.png)

**Comment by nick69g** [comment]
I think a course still needs to be assigned to a company otherwise 
everyone would get and see everything. I'll try and get some clarity as 
it does not seem clear looking at the help ?

**Comment by AnnaHavard** [comment]
OK thanks Nick, in the meantime I’ll just allocate it.



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:imaged45cbb.JPG@c9b960b7.478ba02c]<http://>

[cid:image795da4.PNG@543d58da.4da5ab16]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by AnnaHavard** [comment]
I've set all courses back to closed sharing as they were all appearing on my new user's log in.

**Comment by nick69g** [comment]
I think we had lack of clarity over the sharing options.

No = the course is locked down to just one company (e.g. a bespoke course for them only)
Closed =  the course can be assigned to more than one company (our default option)
Open = the course is assigned to all companies therefore everyone can see it in their course listing
