### ISSUE TITLE
Added Clients on client hub and they are not showing in list of users

### ISSUE THREAD

**Issue by ElaineMills** [CIWM/Client-Hub#14]
Hi Nick,

I added 2 users to the client hub on Friday using the upload method but I forgot to input the passwords on the spreadsheet when I did them. I couldn't find how to add the passwords in so I deleted the users, updated the spreadsheet and tried to re-upload. It wouldn't let me add them again as it said they were already on the system.

I left it alone as I assumed it needed to update the CRON and tried again this morning with Anna's supervision. The upload appeared to work but then we cannot see the users under any company (they should be under Balfour Beatty) or in the user list. 

The users are Hristoslav Tsonkov and Mel Plumpton and if I remember correctly the ID numbers attached by the system were 89 and 90. 

Please can you look into this and let me know if I have done something wrong?

Thanks 
Elaine

**Comment by nick69g** [comment]
OK I'll look into it. Did you upload them whilst in their company area?

**Comment by ElaineMills** [comment]
Yes I uploaded them whilst in Balfour Beatty

**Comment by nick69g** [comment]
OK. I too cannot see them anywhere - can you send me the spreadsheet so 
I can have a look.

Thanks.

**Comment by ElaineMills** [comment]
I can't attach the spreadsheet here so I will email to you.

**Comment by ElaineMills** [comment]
Here is the spreadsheet



        Elaine Mills
        Sales Executive - Training and Development
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823341
Fax:    +44 (0)1604 604467
Email:  elaine.mills@ciwm.co.uk<mailto:elaine.mills@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image747637.JPG@e6bb1a55.4c876a61]<http://>

[cid:image3be902.PNG@916691c1.48b88853]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment]
I've uploaded the two learners with a temporary fix.

One learners email address was .co.uk and the other was .com -I've 
switched these around to be able to get the learners loaded into the Hub 
as Moodle stores and buries deleted accounts/email which I now have to 
try and find in the SQL database. As we are not yet making use of 
automated email this should not be a problem for now.

Username = email address (real one)
Password= Pa$$word1

**Comment by nick69g** [comment]
I've located the two learners within the Moodle database and have updated their email addresses correctly now. The two learners show in Balfour Beatty.

The format for the learner upload spreadsheet is:
username      password      firstname     lastname      email
