### ISSUE TITLE
licencing not working properly

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#15]
My Ground Control user is now set up with the correct course showing on his profile but it says the licence isn't valid:
![gc licence not valid](https://cloud.githubusercontent.com/assets/13269824/9166862/573a2960-3f4b-11e5-8cb5-b51424da6bbc.jpg)
![gc licence allocated](https://cloud.githubusercontent.com/assets/13269824/9166863/573a480a-3f4b-11e5-97fa-a7cb344bdeb2.jpg)

**Comment by ElaineMills** [comment]
Further to this I set myself up as a user for Ground Control and when I go to edit profile I can choose a theme, including ones for other companies. I don't think I should be able to do this should I?

![image](https://cloud.githubusercontent.com/assets/13269835/9167069/cb2ed136-3f4b-11e5-8c26-445a7273a9ee.png)

**Comment by nick69g** [comment]
I created a new license and it worked fine. So I deleted teh old one and 
renamed the new oneto the same - all appears to work OK. Maybe there was 
somethign not quite right in how it was set up?

**Comment by nick69g** [comment]
I've removed this option - it is one of the many default options that 
Moodle thinks you woudl like - it allows a learner to select their own them.
