### ISSUE TITLE
WasteSmart assessment

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#16]
One of my Sodexo users, Sarah Payen, says she has retaken the assessment but her score is not recorded. I anticipate that this was caused by the issue we had with second attempts previously but is there anyway we can check if she went into the system on the date she says she passed? I anticipate we'll need to overwrite her score with the % she says she achieved but I'd like to check the system if possible. 

Her email says - 
I did complete the second attempt at the assessment just before I went on leave (24th July) and passed the course with 72.5% however I was then unable to print the certificate – and on going back into the screen it no longer appeared.

**Comment by AnnaHavard** [comment]
I've found the report on the system that shows that she re-entered the assessment on 24 July, as she states. Given that we know that there was an issue that would have caused her assessment score not be saved please can you go into the system and update her profile to show her higher score. Thanks, Anna

**Comment by nick69g** [comment]
I have updated her score for the WS England & Wales Assessment for 72.5%. This now means that she can access and download the certificate as the pass-mark to get the certificate is 70%.

This is a similar "issue" to what we experienced previously before the settings were changed, so I am closing this issue as this learner has been resolved.

**Comment by AnnaHavard** [comment]
Thanks Nick



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:imagea196c9.JPG@a1d6a021.49829a38]<http://>

[cid:image5e2ffc.PNG@ca585b79.4b83fa54]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.
