### ISSUE TITLE
Courses do not show under My Home and My Courses

### ISSUE THREAD

**Issue by ElaineMills** [CIWM/Client-Hub#18]
Hi,

I registered Garry Heyhurst for WasteSmart and he has now logged in. After changing his password he has clicked my courses and the system shows 'No course information to show'. 
Anna and I have checked all the settings and the course is assigned to him and we have discovered that the issue is not that the course is not in his account but that the system does not show the course under My Home or My Courses. If you click Home the course shows up.

Is it possible to either show the courses under these links or remove the links as this is confusing for the customer?

![garry heyhurst issue](https://cloud.githubusercontent.com/assets/13269835/9379962/dc5c4714-4724-11e5-98f3-12fd54d61a33.png)

**Comment by nick69g** [comment]
The course can be seen under Home, My Home and my Courses. I've "logged in" as Gary and can see the course in all three places. Can you take a screenshot if you see it differently please.

**Comment by nick69g** [comment]
I've also changed the setting so that the default "Home" page for users is now 
    My home / ▶ My courses
Can you check it looks OK to you and then, if so, close the issue.

**Comment by ElaineMills** [comment]
Please can you test this with a new user where the user is required to change their password on log in as when I went into Garry's account earlier I got the same as the screen shot above. 

I cannot now log back into Garry's account as I have set it to force password change and sent him an email to let him know he needs to click home. 

With regards to changing the home page, this is fine as long as the courses do show under here as the customer and I both saw the same thing upon logging in.

**Comment by nick69g** [comment]
OK let me do some tests and check.

**Comment by AnnaHavard** [comment]
Hi Nick, I've just logged into the client hub to check on a user and the screen I'm taken to doesn't show any courses (screen shot below). 

Please can we change the default back to whatever it was previously so we don't confuse those delegates currently using the system when they log in and can't see their courses.  

![image](https://cloud.githubusercontent.com/assets/13269824/9380788/599396e2-472a-11e5-8e70-33ba4ebe2004.png)

**Comment by AnnaHavard** [comment]
They also don't appear under my home only under site home.

**Comment by nick69g** [comment]
OK can you check now. I can see the course under Garry's account.

[cid:68649B90-32DE-4AE2-9CCE-1793550EA8B1]
Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.com<mailto:nick.garrod@cloudsustainability.com>
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.com<http://www.cloudsustainability.com/>

[cid:F732605B-8C39-4256-AE4E-D2970D4D874C] @CloudPioneer<http://twitter.com/cloudpioneer>


[cid:B31CE7D7-0618-416E-A754-233A6DD3DA46]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Cloud Sustainability Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Cloud Sustainability Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.



Please think about the environment before printing this e-mail.

**Comment by AnnaHavard** [comment]
No, still only under Home.

**Comment by nick69g** [comment]
Do you know if this is a new issues. As there is nothing I can now change to influence where and how the courses are seen? Were people not seeing them where they are previously?

**Comment by ElaineMills** [comment]
do you have a way of logging into Garry's account that will not effect the force password thing? I do not want to confuse anything any further as I have already reset the password and sent him an email to let him know this

**Comment by nick69g** [comment]
Yes I can get into it and I see the course in the Home page - the "My home" page I don't think has ever shown courses. But I'm just looking it that now to see if I can remove it. What company/license is Garry under?

Nick

[cid:73099BB0-2E7B-4125-9C43-548F9F69029F]
Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.com<mailto:nick.garrod@cloudsustainability.com>
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.com<http://www.cloudsustainability.com/>

[cid:68549496-9A34-4DED-BB15-3305BADD284C] @CloudPioneer<http://twitter.com/cloudpioneer>


[cid:8C150FC0-8BCD-4998-8DCC-6092E93D5FE2]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Cloud Sustainability Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Cloud Sustainability Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.



Please think about the environment before printing this e-mail.

**Comment by AnnaHavard** [comment]
I don't think they've ever shown under 'my courses' or 'my home' only under 'home'. Our template email that we use to send the log in details to them tell them to go to 'home' to find their courses but it would be good if either they also appeared under 'my home' and 'my courses' or if we remove the 'my home' and 'my courses' link.

**Comment by nick69g** [comment]
Yes - I think that is the case. Looking into this, it appears as though the My Home is a user configurable area so I'm looking to see how My Home and My Courses can be removed as that will keep it neater and more straightforward.

**Comment by ElaineMills** [comment]
Garry is under CIWM Enterprises Ltd

**Comment by nick69g** [comment]
By adding in some HTML code I've removed My Home and My Courses. Please check it looks OK to you.

**Comment by ElaineMills** [comment]
sorry Nick,
This looks ok when I log into my non admin account, thank you.
