### ISSUE TITLE
Course and learner reports

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#2]
Reports not displaying information as expected.

**Comment by nick69g** [comment]
I’ve raised this with IOMAD as I cannot see why the reports are not showing the detail we would expect. I’ve also added it to GitHub which we will run through on Wednesday.

There is a something called a CRON which get’s run in the background in Moodle to update settings etc – I’ve run that and it has increased the count on the reports from 0 to 4.

The IOMAD reports have been built and plugged into Moodle – so you can still view the standard Moodle reports. The one shown below accessible when in the WasteSmart course lists learners that have opened the module and shows what they have completed. This can be exported to Excel and then filtered etc.

**Comment by AnnaHavard** [comment]
I need to provide another report to Sodexo on users progress. Please can you confirm the best report to use for this. I need to show who has logged in and what learning modules they have accessed. Also if anyone has completed and passed the final assessment.

**Comment by nick69g** [comment]
Using the "Activity completion" report within the course and filtering the Sodexo learners is the best one to use at this time until the others within IOMAD have been confirmed working. I chased IOMAD on Friday and will do so again as I've not heard from them which they usually respond quickly.

**Comment by AnnaHavard** [comment]
Hi Nick

Where do I access this, I can’t see a report in Iomad called ‘activity completion’:

[cid:image003.jpg@01D0C2E6.89F36240]

Thanks, Anna



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image59ea12.JPG@381c16d5.4da322dc]<http://>

[cid:image077cfb.PNG@c6a059f5.4eb832ce]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment]
It’s not in Iomad – it is in Course Administration/Reports once in the course page.

**Comment by AnnaHavard** [comment]
Thanks Nick, have found and accessed the reports so this query can be closed.



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:imagef68214.JPG@a0c8eab3.4cb65ed2]<http://>

[cid:image31eb75.PNG@b4814c25.4399bc20]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment]
Closed. Although the "issue" around reporting generally is still open.
