### ISSUE TITLE
Issue reported by Sodexo - programme freezing

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#8]
Have just had the following issue reported by Sodexo, please can you confirm if it's our system or theirs? -  

Unfortunately, as I mentioned the other day, the programme keeps freezing and losing connectivity.
This happened 3 times yesterday in a period of about 15 minutes whilst running through the programme.
When this happens it won’t allow you to continue.
 
You have to go into Task manager, end task and log in again which is quite frustrating.
 
It may be a local issue as my colleague Frank Britt also experienced this last week.

**Comment by nick69g** [comment]
Hi

As they are entering Task Manager and having to end the task (force quit) it sounds as though the freezing is at their end.

Can we find out what browser they are using. Also suggest they check that they are running the latest version of Flash and also that they have a good network connection.

----------------------------------
Nick Garrod
e: nick.garrod@cloudsustainability.com<mailto:nick.garrod@cloudsustainability.com>
m: 07712 331789
s: nickg69

This email has been sent from my iPhone so please excuse any typos!

On 21 Jul 2015, at 10:16, AnnaHavard <notifications@github.com<mailto:notifications@github.com>> wrote:


Have just had the following issue reported by Sodexo, please can you confirm if it's our system or theirs? -

Unfortunately, as I mentioned the other day, the programme keeps freezing and losing connectivity.
This happened 3 times yesterday in a period of about 15 minutes whilst running through the programme.
When this happens it won't allow you to continue.

You have to go into Task manager, end task and log in again which is quite frustrating.

It may be a local issue as my colleague Frank Britt also experienced this last week.

-

**Comment by AnnaHavard** [comment]
Thanks, I’ve requested additional details from the client.



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:imagec60dec.JPG@8be3969b.43867e1e]<http://>

[cid:image4f15c5.PNG@46b80a1e.499d79a7]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by AnnaHavard** [comment]
Second person at Sodexo having similar issue, I have asked them for more info - 

From: Mengham, Kerry 
Sent: 21 July 2015 13:58
To: Atkins-morris, Claire
Subject: RE: 3. FW: WasteSmart report

Hi Claire,

I’m having problems with this site, It keeps freezing then going back to the beginning!

Regards

Kerry

**Comment by nick69g** [comment]
OK. Let me know what they say. Usually "freezing" issues are down to network speeds and/or computers. It should not be related to the client hub or server. But once we know more I can check.

**Comment by AnnaHavard** [comment]
Hi Nick

One person is on IE8 and the other is on IE10. One said that they specifically had the issue on module 2, with the connection dropping out. Both said that they had colleagues who had also experienced issues so I think that’s four people who are having issues.

What would you suggest as a next step?

Thanks, Anna



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:imagee8b356.JPG@b281d2bb.4d910518]<http://>

[cid:image3790af.PNG@327dc7a5.40ae2c14]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment]
OK. I'll run through the module and see if I can replicate any freezing etc?

**Comment by nick69g** [comment]
I’ve worked through about 75% of WasteSmart module 2 without any crashing or freezing issues.

Currently Module 2 shows that 33 learners (Sodexo/Biffa) have access to it. 17 people have successfully completed it, 9 have yet to start it and the remainder have started but not completed.

The fact that 17 people have completed it fully shows there is not an issue with the Module nor LMS – everyone is using exactly the same platform and content.

Troubleshooting advice would be to:

  *   Ensure latest version of browser is being used
  *   Clear cookies/temp files as these can sometimes cause an issue
  *   Try a different browser (Chrome or Firefox) and/or a different computer
  *   Ensure the computer/browser is running the latest version of Flash
  *   Ensure the computer is on a wired network connection and not running over wifi
  *   Try at “less busy” times of the day in the event that multiple users are slowing down the organisations network

**Comment by nick69g** [comment]
It has been difficult to provide a definite solution to this. The reports show a number of learners have successfully completed the module; which demonstrates that it functions as expected.
Often freezing issues can eb down to out of date browsers, slow network connections, old technology, having multiple programmes open at once, etc.
